### ISSUE TITLE
lamson is not starting in shivaAnalyzer environment

### ISSUE THREAD

**Issue by naina-emmanuel** [shiva-spampot/shiva#26]
I am trying to deploy shiva on my ubuntu server 14.04 and have successfully deployed using user manual.pdf from `shiva-spampot/shiva/doc/User Manual.pdf`. At receiver end shiva started successfully but at analyzer end it is giving an error when I run the command **lamson start**.
The error I am getting is:
```
Traceback (most recent call last):
  File "/home/scene/shiva-installer/shiva/shivaAnalyzer/bin/lamson", line 7, in <module>
    args.parse_and_run_command(sys.argv[1:], commands, default_command="help")
  File "/home/scene/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/modargs/args.py", line 381, in parse_and_run_command
    command_module(mod, command, options, cli_options=cli_options)
  File "/home/scene/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/modargs/args.py", line 286, in command_module
    function(**options)
  File "/home/scene/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/lamson/commands.py", line 122, in start_command
    utils.start_server(pid, FORCE, chroot, chdir, uid, gid, umask, loader, debug)
  File "/home/scene/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/lamson/utils.py", line 121, in start_server
    settings.receiver.start()
  File "/home/scene/shiva-installer/shiva/shivaAnalyzer/local/lib/python2.7/site-packages/lamson/server.py", line 265, in start
    mainDb.execute(whitelist)
AttributeError: 'NoneType' object has no attribute 'execute'
```

Please help me in this regard, as everything is working fine including exim just having an issue in starting the lamson at the analyzer end.

**Comment by b0nd** [comment]
Seems some issue with database connection in your setup:
1. mainDb.execute(whitelist) -> mainDb has been reported 'NoneType'
2. It tracebacks to https://github.com/shiva-spampot/shiva/blob/7d7208e96289dc684ebd69b7ed5818d73bbfaffe/analyzer/core/server.py#L261
and that goes to https://github.com/shiva-spampot/shiva/blob/7d7208e96289dc684ebd69b7ed5818d73bbfaffe/analyzer/core/shivadbconfig.py

I would start by checking the sql creds and trying out from normal console if I am being able to connect to the sql server or not.

Cheers!

**Comment by naina-emmanuel** [comment]
I am able to connect to the mysql database with my given credentials in shiva.cof and then successful connection to Shiva and ShivaTemp but still having same error.

**Comment by naina-emmanuel** [comment]
Shiva is working fine. As I have tried to install it on a fresh VM that doesn't have a existing mysql server and it worked fine. 
Thanks
